[package]
name = "trekkie"
version = "0.1.0"
edition = "2021"

[dependencies]
dump-dvb = { path="../dump-dvb.rs" }

#derive_builder = "*"
clap = { version = "4.0", features = ["derive"] }

# webserver shit
#actix-rt = "2.7"
actix = "0.13"
actix-web = "4.0"
actix-diesel = { git = "https://github.com/frol/actix-diesel", branch = "actix-0.13", features = ["actix-web"] }
actix-identity = "*"
actix-session= { version = "0.7", features = ["redis-actor-session"] }
actix-multipart = "*"
derive_more = "0"

# serde serialization / deserialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# database
diesel = { version = "2", features = ["postgres", "r2d2", "uuid", "chrono"] }
r2d2 = "*"

# utils
chrono = "0.4"
uuid = { version = "*", features = ["serde", "v4"] }
#tokio = "*"
env_logger = "*"
log = "*"
rand = "*"
#form-data = "*"
#mime = "*"

futures = "0.3"
utoipa = { path = "../utoipa/utoipa", features = ["actix_extras"] }
utoipa-swagger-ui = { path = "../utoipa/utoipa-swagger-ui", features = ["actix-web"] }
