[package]
name = "trekkie"
version = "0.1.0"
edition = "2021"

[dependencies]
dump-dvb = { version = "0.4", git = "https://github.com/dump-dvb/dump-dvb.rs" }

#derive_builder = "*"
clap = { version = "4.0", features = ["derive"] }

# webserver shit
#actix-rt = "2.7"
actix = "0.13"
actix-web = "4.0"
actix-diesel = { git = "https://github.com/frol/actix-diesel", branch = "actix-0.13", features = ["actix-web"] }
actix-identity = "*"
actix-session= { version = "0.7", features = ["redis-actor-session"] }
actix-multipart = "*"
derive_more = "0"

# serde serialization / deserialization
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

# database
diesel = { version = "2", features = ["postgres", "r2d2", "uuid", "chrono"] }
r2d2 = "*"

# utils
chrono = "0.4"
uuid = { version = "*", features = ["serde", "v4"] }
env_logger = "*"
log = "*"
rand = "*"

futures = "0.3"
utoipa = { version = "2", features = ["actix_extras"] }
#utoipa-swagger-ui = { version = "2", features = ["actix-web"] }

#utoipa = { git = "https://github.com/revol-xut/utoipa.git", features = ["actix_extras"] }


